### ISSUE TITLE
Can't use `daemonize()` method in view constructor

### ISSUE THREAD

**Issue by maratori** [lona-web-org/lona#11]
If I call `self.daemonize()` in `LonaView` constructor, view is not demonized.
That's because after view initialization here
https://github.com/lona-web-org/lona/blob/f70230c520488665092ae291f224278b6425d890/lona/view_runtime.py#L84
field `is_daemon` is reset here
https://github.com/lona-web-org/lona/blob/f70230c520488665092ae291f224278b6425d890/lona/view_runtime.py#L101

Example:

```py
from lona import LonaApp
from lona.view import LonaView

app = LonaApp(__file__)

@app.route("/")
class DaemonView(LonaView):
    def __init__(self, server, view_runtime, request):
        super().__init__(server, view_runtime, request)
        self.daemonize()
        print(self._view_runtime.is_daemon)  # True

    def handle_request(self, request):
        print(self._view_runtime.is_daemon)  # False <- unexpected
        self.daemonize()
        print(self._view_runtime.is_daemon)  # True
        return "html"

app.run(port=8080)
```

**Comment by fscherf** [comment]
``self.daemonize()`` is not meant to be called from the constructor but from ``handle_request()``

Lona views are designed to have ``handle_request()`` as their first callback that is called. Every type of setup should be there

**Comment by maratori** [comment]
Ok.

Not related to daemonization, but I want to say. I prefer to declare all view attributes in constructor to reduce possible surprises.
For example in [multi user chat](https://lona-web.org/cookbook/writing-a-multi-user-view.html), I'd prefer to add following constructor.
```py
class MultiUserChat(LonaView):
    def __init__(self, server, view_runtime, request):
        super().__init__(server, view_runtime, request)
        self.topic = ""
        self.state: Overlay = None
        self.history = Div()
        self.user_list = Div()
        self.text_area = TextArea()
        self.html = HTML()
```

**Comment by fscherf** [comment]
I see, and normally i would agree but the LonaView class requires that the server and runtime references are set correctly (and maybe more in the future). Therefore Lona takes the constructor away from you to make usage more beginner friendly.
