### ISSUE TITLE
External link causes exception in lona.js

### ISSUE THREAD

**Issue by mwx23** [lona-web-org/lona#112]
If I create an external link and click on it `lona.js` throws an exception.

Also it doesn't seem to handle the `target="_blank"` attribute.

```python
from lona import LonaApp, LonaView
from lona.html import HTML, A

app = LonaApp(__file__)


@app.route('/')
class MyView(LonaView):

    def handle_request(self, request):
        html = HTML(
            A(
                'external link to lona',
                href='https://github.com/lona-web-org/lona',
                target='_blank',
            )
        )

        return html


app.run(port=8080)


```

**Comment by fscherf** [comment]
@mwx23 thanks for reporting! Lona nodes have a flag ``ignore`` which tells the client to not patch the default behavior of HTML nodes. Links have a special attribute called ``interactive`` which should enable external links. None of these two properties seem to work in this case and i forgot to document both of them. The client shouln't crash in this case anyway. Much to fix here! :D

**Comment by mwx23** [comment]
No worries @fscherf I don't mean to cause you extra work! :)

I'm hoping in time when I get to know the code better I can submit a pull request instead of just reporting bugs.

**Comment by fscherf** [comment]
@mwx23 Great! :) Contributions are always welcome. If you want i can show you the lines in the code that i think cause the problems instead of fixing them myself, if you search for something to pull-request :)

**Comment by fscherf** [comment]
@mwx23 I've setup a pull-request that fixes the handling of external links, the exception in the client and added some docs on how to use external links in the first place

**Comment by fscherf** [comment]
@mwx23 Both problems are fixed now. I will release 1.7.1 this day
