### ISSUE TITLE
Documentation links are broken

### ISSUE THREAD

**Issue by korantu** [lona-web-org/lona#12]
Cross-reference links in the documentation are pointing to `.rst` pages, where they should be pointing to `.html`.

See for example page https://lona-web.org/end-user-documentation/frontends.html. It has a link to 

_More information:_ [Basic Concept](https://lona-web.org/end-user-documentation/basic-concept.rst)

Defined in:

https://github.com/lona-web-org/lona/blame/master/doc/content/end-user-documentation/frontends.rst#L12

Either documentation has to switch from `.rst` to `.html` in links, or building of the documentation has be fixed.

if someone can advice which approach should be taken, I can have a closer look.

**Comment by fscherf** [comment]
Thanks for reporting! 

Links in rst Syntax 

```text
`link text <link-target.htm>`_
```

have to link to ``.html`` files, links in Flamingo  Syntax

```text
{{ link('link text', 'link-target.rst') }}
```

have to link to ``.rst`` files.
