### ISSUE TITLE
Coverage seems broken

### ISSUE THREAD

**Issue by fscherf** [lona-web-org/lona#132]
Something with the coverage seems odd. How can line 1 be missed, but line 11 run?

![screenshot--2021 09 25-21_45_15](https://user-images.githubusercontent.com/8168821/134784347-cccfa475-b6fe-48a6-a752-9876032767e5.png)

**Comment by sobolevn** [comment]
Do you dynamically recreate / reload modules?

**Comment by fscherf** [comment]
@sobolevn there is code to dynamically load views but this code right here is imported directly

**Comment by sobolevn** [comment]
I've seen problems like this when:
1. `sys.modules` are modified after initial load
2. `pytest` plugin conflict, when some plugin loads your modules before `pytest-cov` does, example:  https://github.com/dry-python/returns/blob/master/tests/conftest.py#L10-L11

**Comment by fscherf** [comment]
@sobolevn Hm. The loading mechanic is a feature i don't want to remove. I had a similar problem in another project a while ago. This line fixed it, but i think it's a hack

https://github.com/pengutronix/aiohttp-json-rpc/blob/master/tox.ini#L47

**Comment by fscherf** [comment]
@sobolevn, @maratori I tried this approach in https://github.com/lona-web-org/lona/tree/fscherf/fix-coverage and it really seems to fix this problem, but is this a good fix? The problem seems to be that the coverage is loaded to late, or is capturing to late.

**Comment by maratori** [comment]
@fscherf I don't know what is the right way to fix it. Here is another example, I've hound https://github.com/pytest-dev/pytest-print/blob/eb776107d83a94e90edeb7381d679251ae45bcf0/tox.ini#L27-L33.

**Comment by fscherf** [comment]
@maratori ah ok! Similar approach but cleaner implemented. To my eyes that looks less like a hack

**Comment by fscherf** [comment]
The problem was solved in #139. @maratori, @sobolevn Thanks for your time!
