### ISSUE TITLE
Your CI does not work

### ISSUE THREAD

**Issue by sobolevn** [lona-web-org/lona#14]
It is broken since the repo was moved to this org:
<img width="1217" alt="Снимок экрана 2021-08-21 в 10 41 28" src="https://user-images.githubusercontent.com/4660275/130314657-22c61eba-bdcb-4dbe-9716-64e47b406a8e.png">

Also, coverage is not found:
<img width="526" alt="Снимок экрана 2021-08-21 в 10 41 58" src="https://user-images.githubusercontent.com/4660275/130314666-9f7a0c5a-9bb1-482b-b526-5deaeabf0349.png">

**Comment by fscherf** [comment]
Hi @sobolevn!

Yes i know, and can't quite figure out why. Travis seems to work, it even builds all PRs, but the checks won't show up beneath the PRs on github. Codecov is enabled for lona-web-org, but the Lona repository won't show up in the codecov interface.

**Comment by sobolevn** [comment]
My 2c: I really recommend swithing from Travis to GitHub Actions. It is way easier. You can take a look at our setup (also has coverage): https://github.com/dry-python/returns/blob/master/.github/workflows/test.yml

**Comment by fscherf** [comment]
@sobolevn: Maybe you are right. Can you provide a prototype config?

**Comment by sobolevn** [comment]
Sure, will submit a PR soon!

**Comment by fscherf** [comment]
@sobolevn: Great, thanks! :) No need to hurry, i test all PRs locally and the test-suite does not cover much currently
