### ISSUE TITLE
SVG Support

### ISSUE THREAD

**Issue by mwx23** [lona-web-org/lona#142]
This might be out of scope, but it would be super cool if you could manipulate `svg` elements with `lona`.

I've tried the following and appears in the DOM when you inspect it, but doesn't render.

```python
from lona import LonaApp, LonaView
from lona.html import Node, HTML

app = LonaApp(__file__)


class Svg(Node):
    TAG_NAME = 'svg'
    ATTRIBUTES = {
        'xmlns': "http://www.w3.org/2000/svg",
    }


class Circle(Node):
    TAG_NAME = 'circle'
    SELF_CLOSING_TAG = True


@app.route('/')
class MyView(LonaView):

    def handle_request(self, request):
        html = HTML(
            Svg(
                Circle(cx="50", cy="50", r="40", stroke="green", stroke_width="4", fill="yellow"),
                width="100",
                height="100",
            )
        )

        return html


app.run(port=8080)
```
I'm working on some widgets that I'll share when they're decent. It was super easy to wire them up, I'm experimenting with different patterns to expose the data back to `lona`. I'll post some new issues with questions I have regarding that.

As per usual, `lona` rocks!

**Comment by fscherf** [comment]
Hi @mwx23,

I thought of this too and started with this: https://github.com/lona-web-org/lona/tree/fscherf/canvas-support

My idea was to add API to use a canvas object in python like in Javascript

```python
from lona.html import Canvas, HTML, H1, P
from lona import LonaView


class CanvasView(LonaView):
    def handle_request(self, request):
        canvas = Canvas(width='300px', height='300px')

        canvas.ctx.lineWidth = 10
        canvas.ctx.strokeRect(75, 140, 150, 110)
        canvas.ctx.fillRect(130, 190, 40, 60)
        canvas.ctx.moveTo(50, 140)
        canvas.ctx.lineTo(150, 60)
        canvas.ctx.lineTo(250, 140)
        canvas.ctx.closePath()
        canvas.ctx.stroke()

        return HTML(
            H1('Canvas'),
            P('This should show a house'),
            canvas,
        )
```

**Comment by fscherf** [comment]
@mwx23 ``SELF_CLOSING_TAG`` gets only used for the server side representation. The client renders tags on its own, without this information. The renderer was not made with SVGs in mind, so maybe we use not the right APIs to handle self closing tags in SVGs correctly.

**Comment by fscherf** [comment]
@mwx23 :)

Sure! When a node gets redered initially ``lona/client/dom-renderer.js`` is used. When a node receives updates ``lona/client/dom-updater.js`` gets used.
