### ISSUE TITLE
SyntaxError: 'return' outside function in the Views documentation examples

### ISSUE THREAD

**Issue by insolor** [lona-web-org/lona#17]
Here is an example code from the [Views](https://lona-web.org/end-user-documentation/views.html):
```python
from lona.view import LonaView
from lona.html import H1
from lona import LonaApp

app = LonaApp(__file__)

@app.route('/')
class MyLonaView(LonaView):
    return H1('Hello World')


app.run()
```
I tried to run the example with Python 3.8.10, and it gives me a syntax error:
```python
    return H1('Hello World')
    ^
SyntaxError: 'return' outside function
```
I guess the return must be inside of the `handle_request` method, like this? At least in this form, it works for me.
```python
from lona.view import LonaView
from lona.html import H1
from lona import LonaApp

app = LonaApp(__file__)

@app.route('/')
class MyLonaView(LonaView):
    def handle_request(self, request):
        return H1('Hello World')

app.run()
```
There are more returns outside of methods on that page and in [Lona Scripts](https://lona-web.org/end-user-documentation/lona-scripts.html). Possibly in some other places too, but I haven't read all the documentation yet.

**Comment by fscherf** [comment]
@insolor: you are completely right, that needs to be in a ``handle_request()`` method. I will fix that later, thaks for reporting :)

**Comment by fscherf** [comment]
@insolor: I have gone through all examples and fixed all issues that i found. Thanks for reporting!
