### ISSUE TITLE
How to use some production-ready table components in this framework

### ISSUE THREAD

**Issue by sylvoslee** [lona-web-org/lona#184]
like ag-grid

**Comment by fscherf** [comment]
Hi @sylvoslee!

Lona has support for Bootstrap 5 tables for example (https://lona-web.org/demos/bootstrap-5-confirmation-popup/index.html)

If you need another frontend library, the documentation has a guide on how to add/package a frontend library (https://lona-web.org/cookbook/integrating-a-frontend-library.html)
