### ISSUE TITLE
Bubble events through multiple layers of widgets

### ISSUE THREAD

**Issue by laundmo** [lona-web-org/lona#197]
Im currently implementing a custom widget that autocompletes a text input field (using jQuery)

The events of the TextInput field should still bubble up to the next widget which is using this one. Currently, that is not the case.

Is there a way to make sure the outer widget receives the events?

<details>
<summary> Code </summary>

```py
class AutocompleteText(Widget):
    FRONTEND_WIDGET_CLASS = "AutocompleteTextWidget"
    STATIC_FILES = [
        StyleSheet(
            name="jquery_ui_css",
            path="static/jquery-ui.css",
            url="jquery-ui.css",
            sort_order=SORT_ORDER.FRAMEWORK,
        ),
        Script(
            name="jquery_min_js",
            path="static/jquery.min.js",
            url="jquery.min.js",
            sort_order=SORT_ORDER.FRAMEWORK,
        ),
        Script(
            name="jquery_ui_js",
            path="static/jquery-ui.js",
            url="jquery-ui.js",
            sort_order=SORT_ORDER.FRAMEWORK,
        ),
        Script(name="autocomplete_widget", path="static/autocomplete-widget.js"),
    ]

    def __init__(self, **kwargs):
        self.text_field_id = "test"
        self.text_field = bs.TextInput(_id=self.text_field_id, **kwargs)
        self.nodes = [Div(self.text_field, _class="ui-widget")]
        self.data = ["#" + self.text_field_id, []]
        # TODO: how to bubble up input events?

    @property
    def autocomplete(self):
        return self.data[1]

    @autocomplete.setter
    def _(self, autocomplete: List[str]):
        self.data = ["#" + self.text_field_id, autocomplete]

    @property
    def value(self):
        return self.text_field.value

    @value.setter
    def _(self, value: str):
        self.text_field.value = value
        
class CommandInputWidget(Widget):
    def __init__(self, **kwargs):
        self.textinp = AutocompleteText(**kwargs, input_delay=0, bubble_up=True)
        self.nodes = [self.textinp]
        self.previous_commands = []

    def handle_input_event(self, input_event):
        if input_event.node is self.textinp:
            if input_event.type == INPUT_EVENT_TYPE.CHANGE:
                self.previous_commands.append(self.textinp.value)
                self.textinp.value = ""
```

</details>

**Comment by fscherf** [comment]
If you are using ``lona.html.TextInput`` you can use the keyword ``bubble_up=True``. To bubble up events in your custom widget, simply return the given input event im you ``handle_input_event`` method.

**Comment by laundmo** [comment]
> Hm. I don't know where bs.TextInput does come from, but if it is either from lona.html or lona_bootstrap5, you seem to use bubble_up correctly.

yeah its from lona_bootstrap5

i had a look at `widget` code and that returns the event by default, so this is odd.

**Comment by fscherf** [comment]
Maybe you found a bug here. Is the code online somewhere, so i can run it myself?

**Comment by laundmo** [comment]
Im actually a bit of a idiot, if you look at my code, i did

```py
class CommandInputWidget(Widget):
    def __init__(self, **kwargs):
        self.textinp = AutocompleteText(**kwargs, input_delay=0, bubble_up=True)
```
which stores the custom widget in self.textinp

but then i do:
```py
    def handle_input_event(self, input_event):
        if input_event.node is self.textinp:
```
comparing the input event node with the `self.textinp`

in other words, i was comparing the node with the widget.

i just had to change the `self.textinp` to reference the actual node the event comes from, and not the widget.

which is easy in my case, but maybe there should be a way to compare the event to the widget it bubbled through?

**Comment by fscherf** [comment]
Ohhh! I missed that too.

There is ``input_event.nodes`` which contains the whole path of elements and widgets. Would that help?

**Comment by laundmo** [comment]
That could work.

What do you think of a built in way to check against any type that it could have bubbled through, to provide a interface that doesn't change between using nodes and widgets?

**Comment by fscherf** [comment]
How would API for something like this look like? My first idea was something like ``node1.contains(node2)``, but this wouldn't say much in this case, because we know that the node we get called with is contained in ``self.nodes``. Otherwise the event wouldn't have bubbled up to us.

**Comment by fscherf** [comment]
@laundmo: ?

**Comment by fscherf** [comment]
I will close this issue for now. Feel free to reopen it if you want to discuss this issue furthe
