### ISSUE TITLE
Client Error in custom Widget - Uncaught (in promise) TypeError: widget is undefined

### ISSUE THREAD

**Issue by laundmo** [lona-web-org/lona#198]
Im experiencing a ClientError when communicating with a custom widget. 

```
Uncaught (in promise) TypeError: widget is undefined
    _run_widget_hooks http://localhost:8080/static/lona/lona.js:1467
    _run_widget_hooks http://localhost:8080/static/lona/lona.js:1463
    _show_html http://localhost:8080/static/lona/lona.js:1528
    add http://localhost:8080/static/lona/lona.js:70
lona.js:1467:32
```

```
LonaWorker_0                   ERROR    19:23:59.862863 lona.view_runtime client error raised:
Lona.LonaWindow/this._run_widget_hooks/<@http://localhost:8080/static/lona/lona.js:1467:32
Lona.LonaWindow/this._run_widget_hooks@http://localhost:8080/static/lona/lona.js:1463:34
Lona.LonaWindow/this._show_html/<@http://localhost:8080/static/lona/lona.js:1528:19
Lona.JobQueue/this.add@http://localhost:8080/static/lona/lona.js:70:27
```

Code can be found here: https://github.com/laundmo/northstar-server-webui

You should be able to run this without anything else running. Then just type something into the textbox and press enter to get the error (will take a while until the connection attempt to the socket it tries to communicate with times out).

(in case its not clear, i give you permission to run it even though it currently doesnt have a license)

**Comment by fscherf** [comment]
Hi @laundmo,

I got it starting by running ``python -m lona run-server --project-root=app -s settings.py`` in the top level of your project but it says 

```
Multiple exceptions: [Errno 111] Connect call failed ('::1', 9998, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 9998)
```

multiple times per second. Can i disable this to see more log?

**Comment by laundmo** [comment]
> GET http://localhost:8080/static/autocomplete-widget.js net::ERR_ABORTED 404 (Not Found)

thats ... wtf? i swear that was working like, just a bit earlier.

thank you, and sorry for not noticing that.

**Comment by fscherf** [comment]
@laundmo no problem!

I happen to have an old example on how to use jquery-ui autocomplete, that i plan on turning into a library at some point. Are you interested in an example how i would implement such a thing? Give me a few minutes and i push a branch for you.

**Comment by laundmo** [comment]
I mean, it works for me the way i have it right now, so theres no immediate need.
Though generally, more pre-made widgets and nodes would be really nice to have.

**Comment by fscherf** [comment]
@laundmo I need this anyway in the future, so it's a good opportunity to collaborate on this :) 

https://github.com/lona-web-org/lona/tree/fscherf/autocomplete

**Comment by laundmo** [comment]
Ah, i see. i think i will keep my solution, as it doesn't require constant requests just for the autocomplete

**Comment by fscherf** [comment]
Good point. I should add an option for local completion where all possible results get transmitted right away. My solution was build with a database in mind where completion on the server makes more sense.

**Comment by laundmo** [comment]
Yeah, for me its for a command history, so it doesn't make too much sense.
