### ISSUE TITLE
Wrong `event.node` for `CheckBox`

### ISSUE THREAD

**Issue by maratori** [lona-web-org/lona#20]
When `CheckBox` fires event, it has wrong attribute `event.node`. I expect to see `CheckBox` itself, but receives `CheckBox.input_node`. Here is an example with workaround.

```py
from lona import LonaApp
from lona.html import CheckBox
from lona.view import LonaView

app = LonaApp(__file__)

@app.route("/")
class CheckBoxView(LonaView):
    def __init__(self, server, view_runtime, request):
        super().__init__(server, view_runtime, request)
        self.checkbox = CheckBox(bubble_up=True)

    def handle_request(self, request):
        return self.checkbox

    def handle_input_event(self, event):
        if event.node == self.checkbox:
            print("this doesn't work")
        if event.node == self.checkbox.input_node:
            print("workaround works")

app.run(port=8080)
```

It seems we need to change `input_event.node` here before return
https://github.com/lona-web-org/lona/blob/a9bd343a347508fa2b9069227b6d2de50fefd881/lona/html/data_binding/inputs.py#L107

**Comment by fscherf** [comment]
@maratori: i see. I think your approach in your pr is right
