### ISSUE TITLE
Hot/live reload feature

### ISSUE THREAD

**Issue by MShekow** [lona-web-org/lona#22]
Hi, did I miss it in the docs, or is there no live/hot reload feature, where changes made to my views are automatically reloaded by the server? If that is the case, I suggest such a feature ;).

**Comment by fscherf** [comment]
Hi @MShekow: Early versions of Lona had such a feature, but it got removed due bad user experience: Reloading a view helps when the view is fully self contained, but when your view uses widgets or helper functions from another module things become inconsistent. Also people use different editors that save files at different times and sometimes multiple times and/or periodically.

Its hard to get this right, therefore i focused on making the server fast to restart and easier to maintain.

If you have an idea how to implement this nicely, i am open for patches (you can find artifacts of my early implementation in the git)

**Comment by themutt** [comment]
I couldn't find the commits related to the reload feature and unfortunately I'm not familiar with aiohttp but I stumbled across [aiohttp-devtools](https://github.com/aio-libs/aiohttp-devtools). Do you think it could be used together with the `run_server()` in `lona`?

**Comment by korantu** [comment]
On the topic of live reloading, is it possible to configure the frontend to try automatically reconnecting after the server restart?

Usecase: `lona` is driving a web UI in a kiosk, and after server update/restart it would be nice to have the view reloaded.

**Comment by fscherf** [comment]
@korantu: Absolutely! The ``test_project`` does this for easier development 

https://github.com/lona-web-org/lona/blob/master/test_project/templates/lona/frontend.html#L106

Sounds like a cool project! Is it available anywhere?

**Comment by fscherf** [comment]
@themutt: ``aiohttp-devtools`` seems to have a similar approach like i had. But it seems only work for scripts, not for whole Lona projects. Also they don't seem to have a solution for changes in modules other than the main script.

To make that a reliable feature you would have to maintain a list of all loaded files and directories, and track changes, file removes and new files. And you have to maintain this list between restarts, to not miss events if files get changed fast like in a git rebase.

I created the reloading mechanism in  https://www.flamingo-web.org/ 
It only tracks changes on ``rst`` files, because i couldn't get python files to work reliable. Also: Its no easy task to track changes in a directory tree, without missing events when big parts get added, removed or moved.

**Comment by MShekow** [comment]
> Its hard to get this right, therefore i focused on making the server fast to restart and easier to maintain.

Thank you for elaborating. Indeed, server-restart is fast. The only annoying part sometimes is to get the UI into the specific state I want to debug, but it is manageable.

The remark about auto-reconnecting the frontend was also very helpful, thanks!

**Comment by fscherf** [comment]
@MShekow:

> The only annoying part sometimes is to get the UI into the specific state I want to debug, but it is manageable.

Yes i agree. Maybe there is a good solution for restart in the future.

I will start an FAQ page with this question and add the client reconnecting snippet to the cookbook.

Thanks for contributing :)

**Comment by korantu** [comment]
@fscherf , auto-reload worked, awesome! Much simpler now. The project is an internal tool/prototype, so, unfortunately, can't share it. The experience is a great success so far, thank you so much! Lona rocks :)

Being able to add a dynamic web UI to a python script this easily is a godsend.

**Comment by fscherf** [comment]
@korantu: Great! :) you are welcome. Very cool that you already use it for something productive :)

@korantu, @themutt: I added an FAQ page, and a recipe with the auto-reconnect snipped. This issue should be resolved now i think
