### ISSUE TITLE
Question: confirmation pop-up in frontend

### ISSUE THREAD

**Issue by MShekow** [lona-web-org/lona#26]
Hi. What is the recommended approach to implement frontend/client-side confirmation using Javascript code such as `confirm("...")`?

The use case is as follows: the Python code of the view generates an HTML table with several rows, one per data item (the data items are fetched from another backend). One of the table columns has a delete button / link. When the user clicks the delete link, I want to show a confirmation pop-up to the user first, to avoid that they accidentally delete items. I only want to handle the input event if the user confirmed the prompt (clicking "Yes").

What I already tried (and it did not work) was to send something like ` A("delete", href=f"javascript:deleteItem('{item.name}')")` to the frontend. When the user then clicks on the link, my javascript code (`deleteItem()`) is not executed (the Web Developer Tools breakpoint does not trigger), but instead I get constant exceptions such as this:
```Uncaught 
Exception { name: "NS_ERROR_FAILURE", message: "", result: 2147500037, filename: "http://localhost:8080/static/lona/lona.js", lineNumber: 1499, columnNumber: 0, data: null, stack: "Lona.LonaWindow/this._handle_websocket_message@http://localhost:8080/static/lona/lona.js:1499:25\nLona.LonaWindow/this.handle_websocket_message@http://localhost:8080/static/lona/lona.js:1572:25\nLona.LonaContext/this._handle_raw_websocket_message@http://localhost:8080/static/lona/lona.js:1852:25\nEventHandlerNonNull*Lona.LonaContext/this.reconnect@http://localhost:8080/static/lona/lona.js:1872:9\nLona.LonaContext/this.setup@http://localhost:8080/static/lona/lona.js:1904:14\n@http://localhost:8080/:41:22\n" }```

**Comment by fscherf** [comment]
Hi @MShekow,

Does the popup has to be a Javascript ``confirm``? I would recommend to use something like bootstrap modals, which are made of html and css.

https://getbootstrap.com/docs/5.0/components/modal/

I made a custom package for my company, based on bootstrap3 which defines Popups using bootstrap3 modals. Works like a charm! I currently work on a public package with the same functionality based on bootstrap 5

**Comment by MShekow** [comment]
Yes, it could totally be the Bootstrap 5 modal. I'm using Bootstrap 5 anyway. I'll try setting up the modal as explained [here](https://getbootstrap.com/docs/5.0/components/modal/#varying-modal-content) (because I need the modal's content to be adaptive, showing the item's name that the user is about to delete).

**Comment by fscherf** [comment]
@MShekow i made a small prototype for you

```python
from lona.html import Widget, HTML, H1, Div, Button
from lona import LonaApp, LonaView

app = LonaApp(__file__)


class Popup(Widget):
    def __init__(self):
        self.nodes = [
            Div(
                Div(_class='popup-title'),
                Div(_class='popup-body'),
                Div(
                    Button('Confirm', _class='confirm'),
                    Button('Cancel', _class='cancel'),
                    _class='popup-buttons'
                ),
                _class='popup'
            )
        ]

        self.confirm_button = self.query_selector('.confirm')
        self.cancel_button = self.query_selector('.cancel')

        self.hide()

    def hide(self):
        self.nodes[0].style['display'] = 'none'

    def show(self):
        with self.lock:
            if 'display' in self.nodes[0].style:
                del self.nodes[0].style['display']

    def set_title(self, *nodes):
        self.nodes[0][0].nodes = list(nodes)

    def set_body(self, *nodes):
        self.nodes[0][1].nodes = list(nodes)


app.add_static_file('lona/style.css', """
    .popup {
        border: 2px solid grey;
        position: absolute;
        top: 0;
        left: 0;
        margin-left: 25%;
        margin-top: 10%;
        height: 4em;
        width: 50%;
    }

    .popup .popup-title {
        font-size: 130%;
        font-weight: bold;
    }

    .popup .popup-buttons {
        float: right;
    }
""")


@app.route('/')
class MyLonaView(LonaView):
    def handle_request(self, request):
        popup = Popup()
        show_popup = Button('Show Popup', _id='show-popup')

        html = HTML(
            H1('Popup Demo'),
            show_popup,
            popup,
        )

        while True:
            input_event = self.await_click(html=html)

            if input_event.node is show_popup:
                with html.lock:
                    popup.set_title('Popup Header')
                    popup.set_body('Popup Body')
                    popup.show()

            elif input_event.node is popup.confirm_button:
                print('confirm was clicked')

                popup.hide()

            elif input_event.node is popup.cancel_button:
                print('cancel was clicked')

                popup.hide()


app.run(port=8080)


```

**Comment by fscherf** [comment]
Hi @MShekow

> Also thank you for the new example you provided. Since I need my view to both regularly refresh data (in the `while` loop of `handle_request()`) _and_ handle click events, I'll probably use `handle_input_event()`. If I understood it correctly, I can simply replace `data = [ ... ]` with `self.data = [ ... ]` (in the first line of `handle_request()`), and then also reference `self.data` in `handle_input_event()`. The content of `self.data` should then be independent for every client.

Yes you are right, you can access ``self.data`` from ``handle_request()`` and ``handle_input_event()`` and that's no hack to do so, its designed that way.

Popup:  In the meantime i released the first version of lona-bootstrap-5 which has native support for modals
https://github.com/lona-web-org/lona-bootstrap-5#modal

Doing two things at the same time: Lona 1.5 has support for callback based input event handling now. Maybe that helps
https://lona-web.org/end-user-documentation/views.html#handling-input-events-in-a-callback

**Comment by fscherf** [comment]
@MShekow In the meantime i added a demo that seems to do pretty much what you are looking for i guess
https://lona-web.org/demos/bootstrap-5-confirmation-popup/index.html
