### ISSUE TITLE
Proposal: Channels

### ISSUE THREAD

**Issue by fscherf** [lona-web-org/lona#299]
# Channels

## Preface

Lona has an API to communicate between multiple instances of views: [View Events](https://lona-web.org/1.x/end-user-documentation/views.html#view-events).
I am not happy with that API, because it is limited to inter-view-communication,
it is always broadcast (if an event gets fired via ``LonaView.fire_view_event()``
every view instance gets to handle that event. You have to implement routing
yourself, if you want to build something like a multiple chat-rooms with
multiple topics) and communication with other parts of the APP like
middlewares, views instances from another class, Django views, Postgres-Hooks
are hard to accomplish.

## Proposal

I propose a fully new API called ``Channel``. Channels are objects, that
consist of a name and a callback, and implement the publish-subscribe-model.
Everyone can open any channel at any time, and can publish and receive
messages.

A channel must have a name, and can have a handler. If the handler is set,
the channel is ready for receiving messages. If not, it is write-only.
The handler can be reset, the name not.

Messages are Python dicts. They can contain anything, but the whole dict has
to be JSON serializable to, so we can support messaging over network, for
example with redis.

In the long run, channels are supposed replace the View Events API.

## Example

```python
from lona import LonaView, Channel


# views.py
class ChatRoomView(LonaView):
    def handle_channel_message(self, channel, message):
        pass

    def handle_request(self, request):
        room_name = request.GET['name']

        # setting up a specific, namespaced channel
        self.channel(f'rooms.{room_name}', self.handle_channel_message)

    def handle_input_event(self, input_event):
        self.channel.send({'message': 'typing...'})


# middlewares.py
class ChatRoomClosingMiddleware:
    async def on_shutdown(self, data):

        # setting up a broadcast channel, connected to all rooms
        channel = Channel('rooms.*')

        channel.send({'message': 'server is about to shut down'})

        # drops all messages that can be dropped
        Channel.shutdown()
```

## API

```python
from lona import LonaView, Channel

# setup
channel = Channel('chat.room')

# send message
channel.send(
    message={'foo': 'bar'},  # user defined payload
    drop=True,               # message may be dropped when the server wants to
                             # to shut down
    expiry=None,             # datetime or timedelta
    priority=100,            # lower means higher priority
)

# set handler at runtime
def handle_chat_message(channel, message):
    print(message)

channel.connect(handle_chat_message)

# disconnect handler
# channel gets removed from global list of channels
channel.disconnect()
```

### Subscribe / Unsubscribe

Channels should be objects. Like this, creation is equivalent to subscribing,
and the channel object can unsubscribe implicitly when it gets deleted.
In the example above, the channel lives exactly as long as the view lives,
without the user having to care about unsubscribing

Channels get created by instantiating the base class. That means the class
has to manage some state in its scope.
Channels are not created using the server or app state. This way any project
component, with any state can always participate.

### Jobs and Messages

A message gets send by invoking ``Channel.send()``. When a message is send, the
channel class puts the message in a priority queue. This priority queue gets
polled by one or multiple tasks or threads.

When the message thread gets a new message, it creates a job for every matching
channel, and puts them into another priority queue, using the messages original
priority.

One or more job worker threads then can run the queued Jobs in parallel.

This distinction between messages and jobs, and the intermediate step with
the first queue is made to make network messaging possible. In the default
configuration the message worker will just create the necessary jobs for a
given message, but we can add a Redis worker that sends messages to a
Redis-server and create jobs when messages come in over the Redis connection.

**Comment by korantu** [comment]
Thank you, @fscherf, for doing this. Is this API also intended to be used for between-tabs communication for same user? Or I am missing something here?

**Comment by fscherf** [comment]
@korantu: Yes! Pretty much for every kind of communication between two or more views (two tabs, mean two views, if the view is not daemonized, which only in some cases makes sense)

**Comment by maratori** [comment]
I don't have a strong opinion about the proposal, but here are a few ideas from me.

1. It's better to avoid global state (inside `Channel` class). It makes code hard to test and restricts some use cases.
2. API isn't clear a bit. It's said that `creation is equivalent to subscribing,
and the channel object can unsubscribe implicitly when it gets deleted`, but I see `channel.connect(handle_chat_message)` and `channel.disconnect()` in API example.
3. Is it possible to send a message before anyone is subscribed channel?
4. Is it possible to create several subscribers to the same channel?
5. Looks like you want to recreate RabbitMQ (or any other message broker). Can we reuse it's API?

**Comment by fscherf** [comment]
@maratori: Thanks for your questions!

## 1
> It's better to avoid global state (inside `Channel` class). It makes code hard to test and restricts some use cases.

I totally agree, and i am not keen on introducing global state either. My first idea was to have the state as part of a object like `ChannelRouter` or `ChannelController` which gets initialized inside the Lona server object. The API would have to be something like this: 

```python
channel = server.create_channel('myView', my_callback)
channel.send({'something-happend': True})
```
I agree, that would be cleaner and easier to test, but that would also make channels only available to parts of a project that have access to the `server` object.
Lona has support for combining Django views or apps with Lona views. This comes in handy when using things like the Django
admin site for example. Currently we have no easy way of communication between Lona code and "traditional" code, we don't share state with.
This API with global state make this possible, and easy to use.

## 2
>  API isn't clear a bit. It's said that `creation is equivalent to subscribing, and the channel object can unsubscribe implicitly when it gets deleted`, but I see `channel.connect(handle_chat_message)` and `channel.disconnect()` in API example.

You are right, the proposal was not very clear in that.
When you create a channel without a message callback, you only have a token to send messages. You can `connect` a callback, to receive messages.

```python
# these two snippets are equivalent:

# snippet 1
channel = Channel('foo', my_callback)

# snippet 2
channel = Channel('foo')
channel.connect(my_callback)
```
The callback has to be registered somewhere, global or local. Therefor it has to unregister when a view ends. Unregister is done using `Channel.disconnect()`.
To avoid boilerplate and user error `Channel.disconnect()` gets called in `Channel.__del__`.
This way you can disconnect without stopping your view, but you don't have to think about cleanup when stopping your view.

```python
# these two snippets are equivalent:

# snippet 1
channel.disconnect()

# snippet 2
del channel
```

## 3,4
> Is it possible to send a message before anyone is subscribed channel?
> Is it possible to create several subscribers to the same channel?

Yes and yes. Channels are inspired by Django Channel and Elixir Channels, and work like busses. You can always subscribe
to anything and publish anything. When publishing a message 0-n subscribers can get the message.

## 5
> Looks like you want to recreate RabbitMQ (or any other message broker). Can we reuse it's API?

The concepts are very similar, but personally i like the Django Channels API. My intention was to have a stripped down version of that, with some influence of Elixir channels. Django Channels have a concept of routing and layers. I like Elixir's approach of wildcards like `Channel('foo.*')` or even `Channel('*')` better.

Do you have some specific RabbitMQ API in mind you would want to use?

**Comment by maratori** [comment]
#### 3

Just to clarify. I send a message A to channel which no one is subscribed. Then someone subscribes the channel. Will it receive message A?

#### 5

> Do you have some specific RabbitMQ API in mind you would want to use?

No, just thinking out loud.

**Comment by fscherf** [comment]
## 3
No. If no one is subscribed, the message gets dropped

**Comment by fscherf** [comment]
The first PR for this is finally ready \o/. In essence, I stuck to the initial design, but I changed the naming of some classes and I scraped the idea of implicit unsubscribe using the garbage collector because it was just too unreliable. I am pretty happy with the results overall.
