### ISSUE TITLE
Imperative event handling

### ISSUE THREAD

**Issue by maratori** [lona-web-org/lona#32]
Currently lona assumes "imperative" way of handling events. I think even for small projects it may be hard to maintain events.
There is the single method `handle_input_event` to react on all events. Usually it contains huge "switch":
```py
    def handle_input_event(self, event):
        if event.node is self.foo:
            ...
        elif event.node is self.bar:
            ...
        ....
```

Don't you think it is a problem?
Do you have any plans to change event handling somehow in the future?

My current approach is to use callbacks and stop event propagation as early as possible. For example I use custom `Button` (the same for other elements).
```py
from typing import Callable
from lona.events.input_event import InputEvent
from lona.html import Button as LonaButton, Widget

class Button(LonaButton, Widget):
    def __init__(
            self,
            *args,
            on_click: Callable[['Button', InputEvent], None] = None,
            bubble_up: bool = False,
            **kwargs
    ) -> None:
        super().__init__(*args, **kwargs)
        self.on_click = on_click
        self.bubble_up = bubble_up

    def handle_input_event(self, event: InputEvent):
        if event.node is self:
            if self.on_click is not None:
                self.on_click(self, event)
            if not self.bubble_up:
                return None
        return event
```

**Comment by fscherf** [comment]
The current design wants yo to create your own widgets, which handle their own events, if your views get more complexe. Currently there are no plans, but i am open to a proposal!

**Comment by maratori** [comment]
I'm not ready to propose something specific. Just like to hear your thoughts for now.

**Comment by fscherf** [comment]
@maratori: I see the problem. The ``LonaView.handle_input()`` API is fine for a few buttons but tedious for many of them. I like the idea of ``button.on_click = $function`` because thats what you would do in Javascript. 

To make it consistent with the existing API i would name the hook ``button.handle_click()`` (in Lona all hooks that can stop an event from blubbling up have prefix ``handle_`` and events that cant be stopped like ``on_shutdown()`` start with ``on_``.

Currently that does not work with the ``Button`` class because only widgets can handle their own input events. We could make a widget of this class or move ``handle_input_event()`` to ``lona.html.AbstractNode``.

I think i would go with the second approach because it would simplify ``lona.html.databinding``. Also it makes more sense. In the browser, every Dom element can handle its own events, not only a few.

**Comment by fscherf** [comment]
@maratori would you review a pull-request for these changes?

**Comment by maratori** [comment]
@fscherf shure

**Comment by laundmo** [comment]
I think a more pythonic way of allowing multiple event handlers would be to allow decorators to be used for that. This is a slight issue, though, as the current proposal uses the HTML object, which won't be available to decorate other methods with. Maybe this could work if the HTML object was defined outside the class, but I'm not sure if that's a good idea.

```py
html = HTML(
    H1('Foo and Bar'),
    Button('Foo', _id='foo'),
    Button('Bar', _id='bar'),
)

class MyLonaView(LonaView):
    @html.query_selector('button.foo').handle
    def on_click(self, input_event):
        pass

    @html.query_selector('button.bar').handle
    def on_click(self, input_event):
        pass

    def handle_request(self, request):
        self.show(html)
```

`html.query_selector('button.bar').handle` here would have to look at the name of the method it's decorating, and use that to decide which event it's handling. (yes, this works even though I defined 2 methods with the same name)

**Comment by fscherf** [comment]
@laundmo: Defining HTML outside the class won't work. Lona creates a new object of ``MyLonaView`` for every request. In your example all objects would access the same object of ``HTML`` which would break updates and state instantly.

I thought of something with decorators too, but the decorated functions would have to be inline functions which costs indentation depth

```python
class MyLonaView(LonaView):
    def handle_request(self, request):
        html = HTML(
            H1('Foo and Bar'),
            Button('Foo', _id='foo'),
            Button('Bar', _id='bar'),
        )

        @html.query_selector('button.foo').handle
        def on_click(input_event):
            pass

        @html.query_selector('button.bar').handle
        def on_click(input_event):
            pass
```

**Comment by laundmo** [comment]
Alternatively, you could split the HTML creation from the request handling, so that Lona can have easy access to the current View's HTML, and then use decorators that are always applied to the current HTML, which don't need the actual instance for decorating.

```py
class MyLonaView(LonaView):
    def create_html(self, request):
        self.html = HTML( # alternatively return html and let lona handle storing it somewhere
            H1('Foo and Bar'),
            Button('Foo', _id='foo'),
            Button('Bar', _id='bar'),
        )
 
    @LonaView.query_selector('button.foo').handle
    def on_click(self, input_event):
        pass

    @LonaView.query_selector('button.bar').handle
    def on_click(self, input_event):
        pass

    def handle_request(self, request):
        html = self.html # or maybe request.html since as you said it would be recreated per request?
```

**Comment by fscherf** [comment]
@laundmo: I thought of something like that in a very early design stage of Lona because thats pretty much how a big jinja template would work. But in Lona you can do things like this:

```python
class MyLonaView(LonaView):
    def handle_request(self, request):
        html = HTML(
            P("Click the Button!"),
            Button('Click me'),
        )

        while True:
            self.show(html)
            self.await_click()

            message = HTML(
                H1('You clicked the button'),
                Button('back to first html'),
            )

            self.show(html)
            self.await_click()
```
Views should not be limited to one big complex HTML tree but should be able to make use of small snippets.

**Comment by laundmo** [comment]
@fscherf i don't quite see how that is mutually exclusive. If you make HTML an attribute of self, you can simply overwrite that from anywhere. Alternatively, let the user define the HTML wherever whenever they want, and self.show() stores the HTML to be used by event handlers. Event handlers would have to be able to cope with not having their selector present in the HTML, but that will have to happen anyway.

Really, my initial idea with having a HTML setup function was bollocks, as the same thing would work just as well without it. The decorator simply needs to know the latest shown HTML.

**Comment by fscherf** [comment]
@laundmo: overwriting means you destroy all state you previous HTML tree had. I think its a useful feature that you can create and manipulate an unlimited amount of trees, not only one that is stored at a specific place.

**Comment by laundmo** [comment]
@fscherf how exactly does the HTML tree's state matter for a on click etc event handler?

**Comment by fscherf** [comment]
@laundmo: Ah! I think i misunderstood you. Do you mean that ``@LonaView.query_selector('button.foo').handle`` from your last example attaches the decorated function to the matching node of the last shown HTML tree? Or does this line get applied to every node tree that ever gets shown?

**Comment by laundmo** [comment]
@fscherf  whichever makes more sense, but i would think the last shown would make the most sense since thats what the user is seeing.

**Comment by fscherf** [comment]
@laundmo interesting Idea. Thats pretty much a routing system for input events. @maratori's proposal has the advantage of being very close to the API you would find in the browser.

**Comment by laundmo** [comment]
@fscherf personally, i like this project because it gets me away from the browser. but once this routing system for input events is in place, adding to it with the syntax @maratori proposed should not be too difficult.

**Comment by fscherf** [comment]
@laundmo I see, but being near to the Javascript API makes explaining the Lona API to beginners very simple, because these are well known concepts by now. Also @maratori's proposal is very simplistic. It does not need a new concept and a new component, but very small changes to the current event system.

I think the idea is very interesting. Maybe that's something for a library on top of Lona like ``lona-web-org/lona-event-router``

**Comment by fscherf** [comment]
@maratori, @laundmo, @maratori: I created #34 which contains all discussed changes.

**Comment by maratori** [comment]
@fscherf I realised only now that new way of handling events do almost the same as in my custom classes, but not completely.

Button click works great:
```py
from lona import LonaApp
from lona.html import HTML, Button, Pre
from lona.view import LonaView

app = LonaApp(__file__)

@app.route("/")
class HandleButtonClicked(LonaView):
    def handle_request(self, request):
        self.button = Button("abc")
        self.button.handle_click = self.button_clicked
        self.pre = Pre()
        return HTML(
            self.button,
            self.pre,
        )

    def button_clicked(self, event):
        self.pre.write_line("button clicked")
        self.show()

app.run(port=8080)
```

But I can't do the same for `TextInput`:
```py
from lona import LonaApp
from lona.html import HTML, Pre, TextInput
from lona.view import LonaView

app = LonaApp(__file__)

@app.route("/")
class HandleTextChanged(LonaView):
    def handle_request(self, request):
        self.text = TextInput(value="abc")
        self.text.handle_change = self.text_changed
        self.pre = Pre()
        return HTML(
            self.text,
            self.pre,
        )

    def text_changed(self, event):
        self.pre.write_line(f"text changed: {self.text.value}")  # <- always "abc"
        self.show()

app.run(port=8080)
```
To make it work I have to manually update `self.text.value = event.data` because following code is not executed.
https://github.com/lona-web-org/lona/blob/master/lona/html/data_binding/inputs.py#L41-L47

Another way is to create a custom class, inherit from `TextInput` and call `super().handle_change(event)`.

**Comment by fscherf** [comment]
@maratori: You are right.  Maybe like this?

```diff
diff --git a/lona/html/data_binding/inputs.py b/lona/html/data_binding/inputs.py
index 46899e6bb844..b17e360e3634 100644
--- a/lona/html/data_binding/inputs.py
+++ b/lona/html/data_binding/inputs.py
@@ -25,7 +25,7 @@ class TextInput(Node):
         if value is not None:
             self.value = value
 
-    def handle_change(self, input_event):
+    def handle_input_event(self, input_event):
         # Data binding nodes catch their own change events and synchronize
         # their internal value. When setting their value, a HTML patch,
         # containing the set value, gets created that gets distributed to all
@@ -38,6 +38,9 @@ class TextInput(Node):
         # The solution for this problem is to don't send patches back to users
         # who issued them.
 
+        if input_event.name != 'change':
+            return input_event
+
         self.attributes.__setitem__(
             'value',
             input_event.data,
@@ -46,6 +49,8 @@ class TextInput(Node):
 
         self.value = input_event.data
 
+        input_event = self.handle_change(input_event)
+
         if self.bubble_up:
             return input_event
```
I am not completely sure about the ``bubble_up`` logic in this case.

Can you reopen this issue? This is obviously not entirely resolved.

**Comment by maratori** [comment]
@fscherf Let me play around with it.

**Comment by mwx23** [comment]
I realise this issue has been closed but I just wanted to share a cool pattern from https://github.com/erdewit/ib_insync that I've found very natural for frameworks with events.

It would look something like this:

```
btn = Button()
btn.on_click_event += my_click_func
```
`on_click_event` being a set of handler functions.
`my_click_func` being a function with the signature for a click input event.

Thanks @fscherf  and @maratori , really enjoying this framework :)

**Comment by fscherf** [comment]
@mwx23 thanks for bringing this up. I thought of something similar to this. My approach was more like the Javascript implementation ``addEvendtHandler``. In the end i decided against it because it makes the API more complex and I could think of a use case that can't be implemented using the simpler API.

**Comment by maratori** [comment]
@mwx23 I thought about `+=` as well. It is like `delegate` in C#. I'm not sure we need this complexity for now.
