### ISSUE TITLE
Installation: directories missing with git install on Windows

### ISSUE THREAD

**Issue by ntnguyen1234** [lona-web-org/lona#327]
When installing Lona via git on Windows

```console
python -m pip install git+https://github.com/lona-web-org/lona.git
```

directories containing javascripts and HTMLs are missing in the package. Installing via PyPi `python -m pip install lona` works correctly.

<details><summary>Screenshot</summary>

![lona](https://user-images.githubusercontent.com/23257168/216347870-ae7b3590-0048-45ca-a6cd-a8640223c15a.png)

</details>

**Environment:**  
- Windows 10 64-bit
- Python 3.11
- `pip` 23.0
- Current Lona version: 1.11

**Comment by fscherf** [comment]
@ntnguyen1234: Thanks for reporting
This seems to be some packaging problem, related to the `MANIFEST.in`. We should switch to `pyproject.toml` anyways, so this seems to be a good opportunity to do so.

Could you please test the new setup?

```
pip install git+https://github.com/lona-web-org/lona.git@fscherf/topic/pyproject-toml
```

**Comment by ntnguyen1234** [comment]
@fscherf I confirm it installs correctly now. Thanks for your update.
