### ISSUE TITLE
lona.html.HTML: add support for high level nodes

### ISSUE THREAD

**Issue by fscherf** [lona-web-org/lona#33]
In #32 @maratori and i agreed on additional API to handle input events more javascript-like:

```python
from lona.html import HTML, H1, Button
from lona import LonaApp, LonaView

app = LonaApp(__file__)


class MyLonaView(LonaView):
    def foo(self, input_event):
        pass

    def bar(self, input_event):
        pass

    def handle_request(self, request):
        html = HTML(
            H1('Foo and Bar'),
            Button('Foo', _id='foo'),
            Button('Bar', _id='bar'),
        )

        html.query_selector('button.foo').handle_click = self.foo
        html.query_selector('button.bar').handle_click = self.bar

        self.show(html)


app.run()
```

The problem is when using HTML strings instead of nodes like this:
```python
from lona.html import HTML, H1, Button
from lona import LonaApp, LonaView

app = LonaApp(__file__)


class MyLonaView(LonaView):
    def foo(self, input_event):
        pass

    def bar(self, input_event):
        pass

    def handle_request(self, request):
        html = HTML("""
            <h1>Foo and Bar</h1>,
            <button id="foo">Foo</button>
            <button id="bar">Bar</button>
        """)

        html.query_selector('button.foo').handle_click = self.foo
        html.query_selector('button.bar').handle_click = self.bar

        self.show(html)


app.run()
```
it's not obvious why the second example does not work.  When``lona.html.HTML`` parses HTML strings, it does not use nodes from ``lona.html.nodes`` but creates them using ``lona.html.Node(tag_name='button')``. Therefore ``Buttons`` and all over inputs that are created that way have no events like ``lona.html.CLICK`` set and have no properties like ``Button.disabled``.

We could add a keyword like ``use_high_level_nodes=True`` (or another name) to ``lona.html.HTML``. If the flag is set the parser would use node classes from the standard library. I would set the flag to true by default. 

@laundmo, @themutt, @maratori, @korantu: Thoughts?

**Comment by themutt** [comment]
Is there a reason for which `lona.html.HTML` does not uses the classes directly from `lona.html.nodes`?

**Comment by laundmo** [comment]
IMO, the default should be that the text HTML is parsed into high level nodes. Ideally, using nodes and text should create equal objects. Maybe even make it possible to have the parser user custom nodes instead?

**Comment by fscherf** [comment]
@themutt: It was just simpler to implement it that way to be honest.

@laundmo: I agree. I want to preserve the possibility to parse into non-high-level nodes, but for most cases high-level nodes are the least surprise. I like the idea with the custom nodes. I would implement a mapping in ``lona.html.nodes`` like this:

```python
NODE_CLASSES = {
    'h1': H1,
    'div': Div,
    ...
}
```

which can be overriden using ``HTML('<div></div>', use_high_level_nodes=True, node_classes={'div': MyDivClass})``

**Comment by maratori** [comment]
I think it's a cool feature to be able parse html string more "correctly".
But I'm not sure it's not worth it.
Parser will become a lot more complex after new nodes is introduced.

**Comment by laundmo** [comment]
@fscherf looks good to me!

@maratori we'll have to see whether @fscherf wants to implement that or not

**Comment by fscherf** [comment]
@maratori, @laundmo:

The parsing code is very simple: https://github.com/lona-web-org/lona/blob/master/lona/html/parsing.py#L24
Only two things would have to be changed to make that work: ``lona.html.nodes`` needs a big registry of nodes that are available, and in this line: https://github.com/lona-web-org/lona/blob/master/lona/html/parsing.py#L42 the parser has to check if a class for the current ``tag_name`` is available.

Very little changes for a very mighty feature in my opinion.

**Comment by maratori** [comment]
@fscherf do you want to use only `Node` and its successors in parsing? Or also want to use widgets as well?

**Comment by fscherf** [comment]
@maratori Only nodes. The only widgets in the standard library besides ``lona.html.HTML`` are the databinding widgets ``TextInput``, ``CheckBox`` etc. I will change them to nodes in my pull-request for #32 because the only reason they are widgets is that nodes can't handle their own input events.

**Comment by maratori** [comment]
@fscherf Ok, now I understand. Indeed in this case parsing is very simple.

**Comment by fscherf** [comment]
@maratori: I created #34 which contains all discussed changes.
