### ISSUE TITLE
How to add Bonsai CSS style tags

### ISSUE THREAD

**Issue by fscherf** [lona-web-org/lona#375]
### Discussed in https://github.com/lona-web-org/lona/discussions/373

<div type='discussions-op-text'>

<sup>Originally posted by **markusgritsch** March 23, 2023</sup>
[Bonsai CSS](https://www.bonsaicss.com/) uses `style` tags of the form `style="--col: 2"`. However, if I try to set such a `style` with Lona, it does not appear in the rendered page. Trying to set `style='color: black'` gets included, but the Bonsai CSS `style` does not work.</div>

**Comment by fscherf** [comment]
@markusgritsch: I created #380, which adds support for non-standard CSS properties

**Comment by markusgritsch** [comment]
Great, thanks a lot! Works fine.
