### ISSUE TITLE
HTML parser does not preserve case of node attributes

### ISSUE THREAD

**Issue by fscherf** [lona-web-org/lona#383]
When a node gets parsed by `lona.html.HTML` all node attributes get converted to lower-case.
```python
>>> HTML('<svg preserveAspectRatio=1></svg>')
<svg data-lona-node-id="4" preserveaspectratio="1"></svg>
```
For HTML, this is fine, but becomes a problem when case-sensitivity is important, for example when rendering SVG nodes.

This issue was uncovered by @markusgritsch in #382

**Comment by markusgritsch** [comment]
Fixed with PR https://github.com/lona-web-org/lona/pull/380
