### ISSUE TITLE
Widgets doesn't initializes correctly

### ISSUE THREAD

**Issue by martinspinler** [lona-web-org/lona#387]
I'm trying to use Bootstrap 5 modal and can't get it working.
There are some undefined variables - at least `widget_class_name` (should be `node_widget_class_name`?) and `node` in 

https://github.com/lona-web-org/lona/blob/b590b0f7bf66421d4132d494a5cfac3c8a68b685/lona/client/_lona/client/dom-renderer.js#L186-L188

**Comment by martinspinler** [comment]
Wow, that was super quick! I can confirm, that my code with Bootstrap Modal now works with this fix.
I can stay up-to-date and enjoy new features like RawHTML. Thank you!

**Comment by fscherf** [comment]
@martinspinler: You are welcome. Thanks for reporting, and testing :)
I released 1.13 (https://lona-web.org/1.x/changelog.html#1.13), which contains the fix
