### ISSUE TITLE
Programmatically focusing TextInput

### ISSUE THREAD

**Issue by gleb-akhmerov** [lona-web-org/lona#388]
Is there a way to programmatically focus the TextInput?

I'm trying to create a simple editor for a list of tags (or categories). Something similar to this: https://github.com/gagan3012/streamlit-tags. I would like to make the TextInput focused by default and also to keep it focused after the user clicks the button to remove a tag.

So far the editor looks like this (simplified the code a bit):

![image](https://user-images.githubusercontent.com/69253059/228836358-62ddab3c-cff3-4398-b271-a67ed3e5c036.png)

```python
from lona import View, App
from lona.html import HTML, Div, Span, Button, TextInput


app = App(__file__)


@app.route("/")
class Index(View):
    def handle_request(self, request):
        tags = ["one", "two", "three"]

        return HTML(
            *(
                Div(Span(t, _style={"margin-right": ".25rem"}), Button("x"))
                for t in tags
            ),
            TextInput(),
        )


app.run()
```

**Comment by fscherf** [comment]
Hi @gleb-akhmerov,

Initial focus is no problem. Just add `autofocus=True` to the TextInput. To refocus an element you will need a [widget](https://lona-web.org/1.x/tutorial/11-widgets/index.html), a small snippet of JavaScript.

I can create a small prototype for you if you want

**Comment by gleb-akhmerov** [comment]
@fscherf, I've added `autofocus=True` to the TextInput, but it didn't help, unfortunately. After some investigation, I've started to think that maybe the reason is that it renders like this (`autofocus="true"` instead of just `autofocus`):

```html
<input data-lona-node-id="33" type="text" autofocus="true" data-lona-events="302:300">
```

Did some more digging and found out that the standard [allows](https://html.spec.whatwg.org/multipage/common-microsyntaxes.html#boolean-attributes) forms like `autofocus=""` and `autofocus="autofocus"`. But still no luck.

Maybe it has something to do with the way Lona works, e.g. autofocus only works on page load, but Lona renders the elements a bit later, changing the layout?

> I can create a small prototype for you if you want

That would be very helpful. And thank you for your help! :smile:

**Comment by fscherf** [comment]
@gleb-akhmerov: I tested the autofocus tag in chrome before answering, but it seems not to work in firefox.
It seems to have to do with timing, because in the example above, i had to add an artificial delay, to force
the browser to reschedule the `element.focus()` call.

To be honest, the example i made for you, is not the cleanest solution, but it will do.
Thanks for this question, i realized two things should be changed on the client side:

1) Boolean properties should be added

2) Currently either the server, or the client can handle a click event. For this example i had to do everything on
the server side, because the client does not support client side event handling and sending them to the server
afterwards (at least not in a convenient way).

I can provide an example that runs more on the client if you want.

```python
from lona.html import HTML, Div, Span, Button, TextInput, H1
from lona.static_files import Script
from lona import View, App

app = App(__file__)


class Tags(Div):
    WIDGET = 'TagsWidget'

    STATIC_FILES = [
        Script(
            name='tags-widget.js',
            path='test-widget.js',
        ),
    ]

    def __init__(self, tags=None):
        super().__init__()

        self.nodes = [
            Div(),
            Div(
                TextInput(),
            ),
        ]

        self.widget_data = {
            'trigger': 1,
        }

        if tags:
            self.set_tags(tags)

    def handle_input_event(self, input_event):
        self.widget_data['trigger'] = self.widget_data['trigger'] * -1

    def set_tags(self, tags):
        with self.lock:
            self.nodes[0].clear()

            for tag_name in tags:
                self.nodes[0].append(
                    Div(
                        Span(
                            tag_name,
                            _style={"margin-right": ".25rem"},
                        ),
                        Button("x"),
                    ),
                )


@app.route("/")
class Index(View):
    def handle_request(self, request):
        self.html = HTML(
            H1('Tags'),
            Tags(["one", "two", "three"]),
        )

        return self.html


app.run()
```

```javascript
class TagsWidget {
    constructor(lonaWindow, rootNode, widgetData) {
        this.rootNode = rootNode;
        this.textInput = this.rootNode.querySelector('input');

        this.focusTextInput();
    }

    focusTextInput() {
        setTimeout(() => {
            this.textInput.focus();
        }, 0);
    }

    onDataUpdated(widgetData) {
        this.focusTextInput();
    }
}


Lona.register_widget_class('TagsWidget', TagsWidget);
```

**Comment by gleb-akhmerov** [comment]
@fscherf,

> To be honest, the example i made for you, is not the cleanest solution, but it will do.

No problem, I can work with that. Thanks!
