### ISSUE TITLE
Performance problems caused by NodeList

### ISSUE THREAD

**Issue by m-reichle** [lona-web-org/lona#401]
We recently updated from lona 1.10 to 1.13 and noted that we are now experiencing performance problems when appending nodes. 
Running our test case through a profiler shows that the majority of time is spent on finding the position of newly added nodes at https://github.com/lona-web-org/lona/blob/master/lona/html/node_list.py#L68.
The index() method is quite expensive, since it runs an \_\_eq\_\_ (and thus two _serialize()) for each node in the list and the new node, every time a node is added, which makes runtime grow very quickly. 

```
               ncalls  tottime  percall  cumtime  percall    filename:lineno(function)
   10 nodes       45    0.000    0.000    0.004    0.000   abstract_node.py:49(__eq__)
  100 nodes    4'950    0.008    0.000    0.319    0.000   abstract_node.py:49(__eq__)
1'000 nodes  499'500    0.882    0.000   33.179    0.000   abstract_node.py:49(__eq__)
```
Collected via `cProfile.run('tr = lona.html.Tr()\nfor i in range(num): tr.append(lona.html.Td(i))', sort='ncalls')`
 
 Another thing we noticed during our testing is that since AbstractNode.\_\_eq\_\_() is called with include_node_ids=False, index() will actually not necessarily return the recently added node, but the first node with equal type and content.

Because of this 

    tr = lona.html.Tr()
    for i in range(num):
      tr.append(lona.html.Td('foo'))

will perform significantly better than 

    tr = lona.html.Tr()
    for i in range(num):
      tr.append(lona.html.Td(i))

This is probably a separate bug, though.

Looking at the code, calling index() seems unnecessary both in NodeList.append() and NodeList.insert() since in both cases the node's index is actually known.

The following patch would remove index() from these methods.

```
diff --git a/lona/html/node_list.py b/lona/html/node_list.py
index 90ea71afdc9f..48edcf456ae5 100644
--- a/lona/html/node_list.py
+++ b/lona/html/node_list.py
@@ -44,8 +44,6 @@ class NodeList:
 
             self._nodes.insert(index, node)
 
-            index = self._nodes.index(node)
-
             self._node.document.add_patch(
                 node_id=self._node.id,
                 patch_type=PATCH_TYPE.NODES,
@@ -57,25 +55,9 @@ class NodeList:
             )
 
     def append(self, value):
-        self._assert_not_frozen()
-        self._check_value(value)
-
         with self._node.lock:
-            node = self._prepare_node(value)
-
-            self._nodes.append(node)
-
-            index = self._nodes.index(node)
-
-            self._node.document.add_patch(
-                node_id=self._node.id,
-                patch_type=PATCH_TYPE.NODES,
-                operation=OPERATION.INSERT,
-                payload=[
-                    index,
-                    node._serialize(),
-                ],
-            )
+            index = len(self._nodes)
+            self.insert(index, value)
 
     def extend(self, nodes):
         self._assert_not_frozen()
```

**Comment by fscherf** [comment]
Hi @m-reichle,

Thanks for your testing, and posting your results. 

> The index() method is quite expensive, since it runs an __eq__ (and thus two _serialize()) for each node in the list and the new node, every time a node is added, which makes runtime grow very quickly.
> [...]
> Another thing we noticed during our testing is that since AbstractNode.__eq__() is called with include_node_ids=False, index() will actually not necessarily return the recently added node, but the first node with equal type and content.

That's true. `AbstractNode.__eq__` gets called implicitly by `list.index` in this case, which is a bug. Using a `==` operation makes no sense in this case. `is` would be the right operation.
We should implement a custom `NodeList.index(node)`, that only compares the ids of its nodes.

> Looking at the code, calling index() seems unnecessary both in NodeList.append() and NodeList.insert() since in both cases the node's index is actually known.

That is not entirely true. I agree, `NodeList.append` can just use the length of the inner node list as new index, but `NodeList.insert` is implemented to work like `list.insert` which accepts out-of-bounds indeces.

```python
>>> l = [1, 2, 3]
>>> l.insert(200, 4)
>>> l
[1, 2, 3, 4]
```

**Comment by ukleinek** [comment]
Ah, I see the flexibility I missed in `insert()`. So alternatively to insert and then search (which would still have quadratic runtime), we could do:

<pre>
diff --git a/lona/html/node_list.py b/lona/html/node_list.py
index 90ea71afdc9f..e1d9aef41781 100644
--- a/lona/html/node_list.py
+++ b/lona/html/node_list.py
@@ -42,9 +42,15 @@ class NodeList:
         with self._node.lock:
             node = self._prepare_node(value)
 
-            self._nodes.insert(index, node)
+            # normalize index
+            if index < 0:
+                index += len(self._nodes)
+                if index < 0:
+                    index = 0
+            if index > len(self._nodes):
+                index = len(self._nodes)
 
-            index = self._nodes.index(node)
+            self._nodes.insert(index, node)
 
             self._node.document.add_patch(
                 node_id=self._node.id,
@@ -57,25 +63,9 @@ class NodeList:
             )
 
     def append(self, value):
-        self._assert_not_frozen()
-        self._check_value(value)
-
         with self._node.lock:
-            node = self._prepare_node(value)
-
-            self._nodes.append(node)
-
-            index = self._nodes.index(node)
-
-            self._node.document.add_patch(
-                node_id=self._node.id,
-                patch_type=PATCH_TYPE.NODES,
-                operation=OPERATION.INSERT,
-                payload=[
-                    index,
-                    node._serialize(),
-                ],
-            )
+            index = len(self._nodes)
+            self.insert(index, value)
 
     def extend(self, nodes):
         self._assert_not_frozen()
</pre>

**Comment by fscherf** [comment]
@ukleinek: Nice! But we will still need a custom `NodeList.index()` because currently it just calls `list.index()`, which returns incorrect results.

**Comment by ukleinek** [comment]
> @ukleinek: Nice! But we will still need a custom `NodeList.index()` because currently it just calls `list.index()`, which returns incorrect results.

Agreed in principle. However I'm not sure that it's a good idea to call this function `index()` because the semantic difference to `List.index()` might be surprising.

Sidenote: The index lookup (both `List.index()` and your idea for `NodeList.index()`) could be (depending on the use case quite a bit) more effective, if `_serialize()` would be lazy (or __eq__ would not just compare complete serializations). Consider a comparison between a Div and a P object, both with several big children, with ==. Then __eq__ first serializes the complete content of both nodes before noticing that their types are different.

**Comment by fscherf** [comment]
@ukleinek:

> Agreed in principle. However I'm not sure that it's a good idea to call this function index() because the semantic difference to List.index() might be surprising.

Yes, you are right.

On `AbstractNode.__eq__` calling to `AbstractNode._serialize`: Maybe we should get rid of this entirely, and just compare all node attributes of two different nodes. Best case, we can return `False` on the first check (`self.tag_name == other.tag_name`), without serializing.
