### ISSUE TITLE
Lona Hot Reload

### ISSUE THREAD

**Issue by eldjoko** [lona-web-org/lona#422]
Hi,

Are there any plans to support hot reloading for Lona apps ?

it would be tremendously helpful to have that features for developers. Currently, i use `watchfiles`  to detect any code changes in the folder and restart the script, but this produces a side effect that server shows disconnected in the browser.

Thank you!

**Comment by fscherf** [comment]
Hi @eldjoko,

Not having hot-reload was an active design-decision: https://lona-web.org/1.x/faq.html#why-has-lona-no-live-reload-feature-like-aiohttp-devtools

Maybe I would be open to a solution when someone had a good concept for testing such a feature and would be willing to maintain it.
