### ISSUE TITLE
AttributeError when comparing nodes

### ISSUE THREAD

**Issue by m-reichle** [lona-web-org/lona#433]
Hi,

the new version of `Abstract Node.__eq__()` has me run into errors with custom nodes that do not implement the attributes tested in `__eq__`. I'd say if the `AbstractNode` class has a method that assumes the existence of attributes, those should either have defaults or there should be a `hasattr()` beforehand. Not sure which would make more sense here.

I'd propose verifying this in a very basic test such as this.

```
from lona.html.abstract_node import AbstractNode

an1 = AbstractNode()
an2 = AbstractNode()

assert an1 == an1
assert an1 != an2
```

**Comment by fscherf** [comment]
Hi @m-reichle,

`lona.html.abstract_node.AbstractNode` is not intended to be inherited from in application code. `lona.html.Node` is what you are presumably searching for. Or is there any reason for you to use the abstract class instead?

**Comment by m-reichle** [comment]
I'm inheriting from `Widget`, which in turn inherits from `AbstractNode`.

**Comment by fscherf** [comment]
I see. Im this case this should be fixed. I would recommend using `lona.html.Node` instead though since `lona.html.Widget` is deprecated and will be removed in Lona 2. `lona.html.Node` has all fearures of `lona.html.Widget` now, so porting is pretty fast-forward

**Comment by fscherf** [comment]
@m-reichle: I opened #434 to fix this issue

**Comment by fscherf** [comment]
@m-reichle: can you verify if the PR fixes the problem?

**Comment by m-reichle** [comment]
Will do
