### ISSUE TITLE
Question: how i can deploy lona apps for free?

### ISSUE THREAD

**Issue by nacho00112** [lona-web-org/lona#455]
There are any services that does this with lona? There already are with flask

**Comment by fscherf** [comment]
Hi @nacho00112!
There are no hosting services that offer Lona app hosting, that I am aware of, but Lona is pretty easy to start in a docker container. So any service that offers docker containers should be fine

**Comment by nacho00112** [comment]
> Hi @nacho00112! There are no hosting services that offer Lona app hosting, that I am aware of, but Lona is pretty easy to start in a docker container. So any service that offers docker containers should be fine

Then may be a good idea to include this theme in the documentation, and also would be cool if lona autogenerates the docker files by itself

**Comment by fscherf** [comment]
@nacho00112: Yes you are absolutely right, and it's been on the wishlist for ages. I will create an issue for it.

**Comment by nacho00112** [comment]
> @nacho00112: Yes you are absolutely right, and it's been on the wishlist for ages. I will create an issue for it.

Please bro your project is exactly what i'm looking for is very good

**Comment by fscherf** [comment]
Ok :) i'll try to do it this weekend, or next week. Can you review/test the pull-request?

**Comment by fscherf** [comment]
@nacho00112: https://lona-web.org/1.x/deployment/deploying-on-docker.html
I hope this helps. Let me know if some information is missing

**Comment by nacho00112** [comment]
What that COPY means? I have to use it with all my app files? Using path globs?

**Comment by fscherf** [comment]
In the dockerfile? That means all contents of the current directory get copied to the image

**Comment by nacho00112** [comment]
> In the dockerfile? That means all contents of the current directory get copied to the image

**Comment by fscherf** [comment]
All contents, including `hello-world.py`

**Comment by fscherf** [comment]
Can we close this issue?
