### ISSUE TITLE
Question: Authentication with Firebase

### ISSUE THREAD

**Issue by camstuart** [lona-web-org/lona#461]
Hello,

is there any examples or documentation that we could use to implement authentication with Firebase?

Thanks

**Comment by fscherf** [comment]
Hi @camstuart,

No. Currently, there is no ready-to-use authentication for firebase, but it shouldn't be too hard to set it up.
Take a look at [lona-django](https://github.com/lona-web-org/lona-django). It implements django auth using a simple middleware.

What you will have to do is set up (or use) a firebase specific user objects (https://github.com/lona-web-org/lona-django/blob/master/lona_django/middlewares.py#L45) and set it in `connection.user`. Your middleware can then implement a `handle_request` method to limit access to some views.

**Comment by camstuart** [comment]
> 

Thanks @fscherf I'll give it a try, your instructions are very helpful

**Comment by fscherf** [comment]
Let me know if you encounter any problems. Also let me know if this is something for https://github.com/lona-web-org
maybe lona-firebase or so

**Comment by camstuart** [comment]
> @camstuart: Did you get it working?

Sorry, haven't had time. I about to walk the camino de santiago to digital detox! but when i return in November this is on the top of my list

**Comment by fscherf** [comment]
Hi @camstuart! Any progress on this issue? It is open for a while now.

**Comment by camstuart** [comment]
> Hi @camstuart! Any progress on this issue? It is open for a while now.

Afraid not, I decided to go with a straight react ui to keep with the most common tech. Best to close I think

**Comment by fscherf** [comment]
@camstuart no problem! :) Feel free to reopen the issue If you want to revisit the topic
