### ISSUE TITLE
Support for gunicorn

### ISSUE THREAD

**Issue by nacho00112** [lona-web-org/lona#472]
I can't run lona apps with [gunicorn](https://github.com/benoitc/gunicorn)

**Comment by fscherf** [comment]
Could you provide more information on what you are trying and why you need gunicorn?

**Comment by nacho00112** [comment]
> Could you provide more information on what you are trying and why you need gunicorn?

I was trying to avoid apache2 because i don't like those long configuration files, but now i discovered that gunicorn does not have what i want

**Comment by fscherf** [comment]
I recommend nginx :)

**Comment by nacho00112** [comment]
> I recommend nginx :)

My server provider uses apache2 so i tried to change it but i can't, the only thing i can do is to put the files like index.html or index.php in a public_html directory, but lona does not work of that way i guess it generates the html dynamically, so i'm considering to talk with the provider about this

**Comment by fscherf** [comment]
Yeah, I am afraid that won't work. Lona can be used with Apache2 but Lona speaks HTTP and does not create HTML files. If you want to use it with Apache you will need a config similar to this: https://lona-web.org/1.x/deployment/deploying-on-linux.html#id1
