### ISSUE TITLE
the `tests` directory is present in the source packages

### ISSUE THREAD

**Issue by fscherf** [lona-web-org/lona#475]
Since we use the `pyproject.toml` the `tests` folder is always part of the source packages. I attempted to fix that multiple times and failed.

@sobolevn: Do you have an idea what I am doing wrong?

**Comment by sobolevn** [comment]
Why do you think that this should be fixed? Many maintainers are asked to do exactly this.
Check out https://github.com/typeddjango/pytest-mypy-plugins/issues/114

**Comment by fscherf** [comment]
Oh Interesting! My intention was to decrease the package size and overall shipped Python files. Also, the files end up next to the `lona` package, not in it. It also bothers me that I can't shut this behavior off, so its no deliberate decision to ship the tests.

**Comment by fscherf** [comment]
Ah! You are right. According to https://packaging.python.org/en/latest/guides/using-manifest-in/#how-files-are-included-in-an-sdist it is best practice to include your tests into an sdist. It's a bit weird to me, but ok then. Thanks for your help!
