### ISSUE TITLE
`AttributeList` is a `set` actually, but `list` is used under the hood

### ISSUE THREAD

**Issue by maratori** [lona-web-org/lona#48]
`AttributeList` is a `set` actually, but `list` is used under the hood (`AttributeList._attributes`).
This causes performance problems on high number of items.

**Comment by fscherf** [comment]
@maratori: You are right. When using something like Tailwind, this could be a problem.

**Comment by maratori** [comment]
@fscherf, I'm going to create PR. Do you think I should rename `AttributeList` to `AttributeSet`?

**Comment by fscherf** [comment]
@maratori: No because they are meant to implement an abstraction for ``node.class_list`` and ``node.id_list`` in the browser. You are right, they should use sets, because javascript infact handles these proberties like python sets, but the name should stay.
