### ISSUE TITLE
Boolean attributes doesn't work

### ISSUE THREAD

**Issue by maratori** [lona-web-org/lona#49]
Some "boolean" attributes doesn't work as expected. Below is an example.
```py
from lona import LonaApp
from lona.html import HTML, Select, Button
from lona.view import LonaView

app = LonaApp(__file__)

@app.route("/")
class AttributesWithoutValue(LonaView):
    def handle_request(self, request):
        return HTML(
            Select(values=[(1, "aaa"), (2, "bbb")], multiple=False),  # actually it is multiple in browser
            Button("xxx", disabled=False),  # actually it is disabled in browser
        )

app.run(port=8080)
```

@fscherf What do you think if we will handle such special attributes (`disabled`, `checked`, `multiple`, ...) in `AttributesDict` class?
For example if I execute `node.attributes["disabled"] = False` it will remove `disabled` attribute from html.

**Comment by fscherf** [comment]
@maratori: Good idea! Can you make a pr for this?

**Comment by maratori** [comment]
@fscherf sure, I'm on it.

**Comment by maratori** [comment]
@fscherf I'm working on PR and need to decide what behaviour should be.

I see three options. Following tables show the difference.
* Option 1 - works as ordinary `dict` (except conversion `str` to `True`)
* Option 2 - `... = False` behaves the same as `del`
* Option 3 - more like html attributes, but may seem inconsistent for someone

What do you think?

| `node.attributes['disabled'] = True`<br>or<br>`node.attributes['disabled'] = 'any string'` | All options |
| :---                                                                                       | :---        |
| `'disabled' in node.attributes.keys()`                                                     | `== True`   |
| `('disabled', True) in node.attributes.items()`                                            | `== True`   |
| `node.attributes.pop('disabled')`                                                          | `== True`   |
| `node.attributes.get('disabled')`                                                          | `== True`   |
| `node.attributes['disabled']`                                                              | `== True`   |
| `'disabled' in node.attributes.__iter__()`                                                 | `== True`   |
| `'disabled' in node.attributes`                                                            | `== True`   |

| `node.attributes['disabled'] = False`            | Option 1   | Option 2   | Option 3   |
| :---                                             | :---       | :---       | :---       |
| `'disabled' in node.attributes.keys()`           | `== True`  | `== False` | `== False` |
| `('disabled', False) in node.attributes.items()` | `== True`  | `== False` | `== False` |
| `node.attributes.pop('disabled')`                | `== False` | `KeyError` | `== False` |
| `node.attributes.get('disabled')`                | `== False` | `KeyError` | `== False` |
| `node.attributes['disabled']`                    | `== False` | `KeyError` | `== False` |
| `'disabled' in node.attributes.__iter__()`       | `== True`  | `== False` | `== False` |
| `'disabled' in node.attributes`                  | `== True`  | `== False` | `== False` |

| `del node.attributes['disabled']`<br>or<br>`node.attributes.pop('disabled', False)` | Option 1   | Option 2   | Option 3   |
| :---                                                                                | :---       | :---       | :---       |
| `'disabled' in node.attributes.keys()`                                              | `== False` | `== False` | `== False` |
| `('disabled', False) in node.attributes.items()`                                    | `== False` | `== False` | `== False` |
| `node.attributes.pop('disabled')`                                                   | `KeyError` | `KeyError` | `== False` |
| `node.attributes.get('disabled')`                                                   | `KeyError` | `KeyError` | `== False` |
| `node.attributes['disabled']`                                                       | `KeyError` | `KeyError` | `== False` |
| `'disabled' in node.attributes.__iter__()`                                          | `== False` | `== False` | `== False` |
| `'disabled' in node.attributes`                                                     | `== False` | `== False` | `== False` |

**Comment by fscherf** [comment]
@maratori i think i would go with a combination of 1 and two. If we define ``disabled`` as boolean attribute it should have always a value. Also only boolean values should be allowed.

```
d = Div()
d.attributes['disabled'] -> False
d.attributes['disabled'] = True
d.attributes['disabled'] -> True
d.attributes['disabled'] = 'some string' -> ValueError
```

When using ``pop()``, ``del`` etc i would set ``False`` as value

**Comment by maratori** [comment]
@fscherf I'm not sure it is good idea because I expect that if `'disabled' in node.attributes`, then it is disabled. Because that's how html works. But actually it means nothing and I have to check the value.

**Comment by fscherf** [comment]
@maratori Good point.

```python
d = Div()
'disabled' in d.attributes -> False
d.disabled = False
'disabled' in d.attributes -> False
d.disabled = True
'disabled' in d.attributes -> True
```

Is this to much magic?

**Comment by maratori** [comment]
> Is this to much magic?

I don't know :)
That's why I'm asking before implementation.

**Comment by fscherf** [comment]
@maratori Maybe its easier to just fix the node properties and keep ``AttributeDict`` a simple data store. There are 3 maybe 5 boolean attributes i can think of, and only a handful of nodes that require them.

Also: Whats about older or exotic browsers that need something like ``checked="checked"``?

**Comment by maratori** [comment]
@fscherf agree. I came up to the same conclusion.

**Comment by fscherf** [comment]
@maratori Are you working on a pr or should i start working on this?

**Comment by maratori** [comment]
@fscherf I started with the original idea. But after we discarded it I haven't done the new one yet. So go ahead, if you want.

**Comment by fscherf** [comment]
@maratori i will create a pr then :)
