### ISSUE TITLE
Minimal python version and f-strings

### ISSUE THREAD

**Issue by maratori** [lona-web-org/lona#54]
What is the minimal supported python version?
Can we use f-strings? It would be great if yes.

**Comment by fscherf** [comment]
Currently the minimal supported version is 3.6 like in aiohttp. So f-strings are ok with me.

**Comment by maratori** [comment]
Don't you mind if I create a PR to convert all formatting to f-strings?

**Comment by fscherf** [comment]
@maratori  Sure, go ahead! That sounds very tedious, i feel bad that you put so much work in this :D

**Comment by maratori** [comment]
@fscherf don't worry, that's how I relax :)
